options:
  formatter: stylish
  merge-default-rules: false
rules:
  class-name-format:
    - 0
  indentation:
    - 0
  empty-line-between-blocks:
    - 1
    - ignore-single-line-rulesets: true
  property-sort-order:
    - 1
    -
      order:
        - position
        - top
        - right
        - bottom
        - left
        - z-index
        - float
        - clear
        -
        - display
        - flex
        - flex-direction
        - flex-wrap
        - align-items
        - justify-content
        - visibility
        - overflow
        - overflow-x
        - overflow-y
        - box-sizing
        - size
        - width
        - min-width
        - max-width
        - height
        - min-height
        - max-height
        - padding
        - padding-top
        - padding-right
        - padding-bottom
        - padding-left
        - border
        - border-top
        - border-right
        - border-bottom
        - border-left
        - border-width
        - border-top-width
        - border-right-width
        - border-bottom-width
        - border-left-width
        - border-style
        - border-top-style
        - border-right-style
        - border-bottom-style
        - border-left-style
        - border-color
        - border-top-color
        - border-right-color
        - border-bottom-color
        - border-left-color
        - border-radius
        - border-top-left-radius
        - border-top-right-radius
        - border-bottom-left-radius
        - border-bottom-right-radius
        - margin
        - margin-top
        - margin-right
        - margin-bottom
        - margin-left
        -
        - transform
        - transform-origin
        -
        - background
        - background-image
        - background-color
        - background-position
        - background-repeat
        - background-size
        - background-attachment
        - opacity
        - box-shadow
        -
        - color
        - font-family
        - font-size
        - font-weight
        - line-height
        - text-align
        - text-decoration
        - text-transform
        - text-shadow
        - list-style-type
        -
        - cursor
        - transition
        - transition-property
        - transition-timing-function
        - animation
